### ISSUE TITLE
Consider adding to conda-forge

### ISSUE THREAD

**Issue by jcox10** [sandialabs/reverse_argparse#42]
Consider adding this package to [conda-forge](https://conda-forge.org/docs/maintainer/adding_pkgs.html). This would enable it to be easily integrated into anaconda environments.

**Comment by jmgate** [comment]
This is a great idea!  Have you done something like this before?  I'm sure it's probably pretty straightforward; I just don't have any experience with it yet.

**Comment by jmgate** [comment]
🤦 It helps if you click on links before responding.  Thanks for the instructions 🤣

**Comment by jmgate** [comment]
Looks straightforward enough.  I'll get right on it.

**Comment by jmgate** [comment]
This should be the necessary `meta.yaml` recipe:
```yaml
{% set name = "reverse-argparse" %}
{% set version = "1.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/reverse_argparse-{{ version }}.tar.gz
  sha256: 319f36675606ae2dd465f8fa860e4ec18a78598a261b91f8b715e1f1a570dc25

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - poetry-core
    - pip
  run:
    - python >=3.8

test:
  imports:
    - reverse_argparse
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sandialabs/reverse_argparse
  summary: Generate the effective command line invocation for a script.
  license: BSD-3-Clause
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - jmgate

```
